swagger: "2.0"
info:
  description: "This is CalcuCo's awesome calculator. <br> <br>Operation supported: <br> <ol><li>Add - `add` </li> <li>Subtract - `sub`</li><li>Multiply - `multi`</li><li>Divide - `div`</li><li>Square root - `sqrt`</li><li>Qubic root - `cbrt`</li><li>Power - `pow`</li><li>Factorial - `fac`</li><ol>"
  version: "1.0.0"
  title: "CalcuCo's calculator"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v1"
tags:
- name: "report"
  description: "Event's API information"
schemes:
- "http"
paths:
  /report:
    get:
      tags:
        - report
      operationId: findReports
      parameters:
        - name: start
          in: query
          type: string
          format: date-time
        - name: end
          in: query
          type: string
          format: date-time
      responses:
        200:
          description: list all events
          schema:
            type: array
            items:
              $ref: "#/definitions/report"
        default:
          description: generic error
          schema:
            $ref: "#/definitions/error"
      security:
        - key: []
  /calc/{operation}/{args}:
    parameters: 
      - name: operation
        in: path
        type: string
        pattern: "^(add|sub|multi|div|sqrt|cbrt|pow|fac)$"
        required: true
      - name: args
        in: path
        type: array
        items:
          type: integer
          format: int64
        required: true
    get:
      tags:
        - calc
      summary: "Performs mathematical computations"
      description: "Operation would either be: <ol><li>Add - `add` </li> <li>Subtract - `sub`</li><li>Multiply - `multi`</li><li>Divide - `div`</li><li>Square root - `sqrt`</li><li>Qubic root - `cbrt`</li><li>Power - `pow`</li><li>Factorial - `fac`</li><ol>"
      operationId: calcOperation
      responses:
        200:
          description: OK
          schema:
            type: integer
            format: float64
        default:
          description: generic error
          schema:
            $ref: "#/definitions/error"
      security:
        - key: []

securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-token

definitions:
  report:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      type:
        type: string
      user:
        type: string
      message:
        type: string
      createdDate:
        type: string
        format: date-time
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"